# Application Name
spring.application.name=intellibank
server.port=8081

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/intellibank
spring.datasource.username=postgres
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
# Base64 encoded secret key (min 256 bits for HMAC-SHA256)
# e.g., 'my-secret-key-that-is-at-least-32-bytes-long' -> base64 -> bXktc2VjcmV0LWtleS10aGF0LWlzLWF0LWxlYXN0LTMyLWJ5dGVzLWxvbmc=
jwt.secret=bXktc2VjcmV0LWtleS10aGF0LWlzLWF0LWxlYXN0LTMyLWJ5dGVzLWxvbmc=
jwt.issuer=intellibank
